trigger:
- release
- dev

jobs:
#- job: Linux
#  pool:
#    vmImage: 'ubuntu-20.04'
#  steps:
#  - script: |
#      sudo apt-get -qq update;
#      sudo pip install --upgrade pip
#      sudo apt-get install python-setuptools;
#      sudo apt-get install libglew-dev libxrandr-dev libxxf86vm-dev libxcursor-dev libxinerama-dev libxi-dev
#      sudo python build_scripts/build_osd.py --tests --tbb --omp --build $HOME/OSDgen/build --src $HOME/OSDgen/src $HOME/OSDinst
#    displayName: 'Building OpenSubdiv'
#  - script: |
#      cd $HOME/OSDgen/build/s
#      sudo ctest -T test -R "bfr|far"
#    displayName: 'Testing OpenSubdiv'
#  - task: PublishTestResults@2
#    inputs:
#      testResultsFormat: cTest
#      testResultsFiles: /home/vsts/OSDgen/build/s/Testing/*/Test.xml
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'osd-linux'
#      targetPath: "/home/vsts/OSDinst"


#- job: macOS
#  pool:
#    vmImage: 'macOS-11'
#  steps:
#  - script: |
#      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer"
#      python build_scripts/build_osd.py --tests --tbb --generator Xcode --build $HOME/OSDgen/build --src $HOME/OSDgen/src $HOME/OSDinst
#    displayName: 'Building OpenSubdiv'
#  - script: |
#      cd $HOME/OSDgen/build/s
#      ctest -T test -R "bfr|far"
#    displayName: 'Testing OpenSubdiv'
#  - task: PublishTestResults@2
#    inputs:
#      testResultsFormat: cTest
#      testResultsFiles: /Users/runner/OSDgen/build/s/Testing/*/Test.xml
#  - task: PublishPipelineArtifact@0
 #   inputs:
  #    artifactName: 'osd-macOS'
  #    targetPath: "/Users/runner/OSDinst"

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
          MD build
  - script: |
        git clone https://github.com/microsoft/vcpkg.git --depth 1
    displayName: 'Get vcpkg'
    workingDirectory: build
  - script: |
        .\bootstrap-vcpkg.bat
    displayName: Bootstrap vcpkg
    workingDirectory: build\vcpkg
#  - script: |
#        .\vcpkg.exe install openssl --vcpkg-root ./
#        .\vcpkg.exe list
#    displayName: Install OpenSSL
#    workingDirectory: build\vcpkg
  - script: |
        .\vcpkg.exe install glfw3 --vcpkg-root ./
        .\vcpkg.exe list
    displayName: Install GLFW
    workingDirectory: build\vcpkg   
  - script: |
      echo "calling vcvars64.bat"
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      echo "using python3"
      cmake -G "Visual Studio 16 2019 -A x64" -D NO_PTEX=1 -D NO_DOC=1 -D NO_OMP=1 -D NO_TBB=1 -D NO_CUDA=1 -D NO_OPENCL=1 -D NO_CLEW=1 -D "GLFW_LOCATION=build\vcpkg\glfw3"
      cmake --build . --config Release --target install
     # call python3 build_scripts/build_osd.py --generator "Visual Studio 16 2019" --generatorPlatform "x64" --tests --tbb --omp --build %HOME%/OSDgen/build --src %HOME%/OSDgen/src %HOME%/OSDinst
    displayName: 'Building OpenSubdiv'
  - script: |
      cd %HOME%/OSDgen/build/s
      ctest -T test -R "bfr|far"
    displayName: 'Testing OpenSubdiv'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: D:/OSDgen/build/s/Testing/*/Test.xml
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'osd-win64'
      targetPath: "D:/OSDinst"


#  - job: windows
#    displayName: 'Build - Windows'
#    continueOnError: false
#    pool:
#      vmImage: 'windows-latest'
#    workspace:
#      clean: all
#    steps:
#      - script: |
#          MD build
#      - script: |
#          git clone https://github.com/microsoft/vcpkg.git --depth 1
#        displayName: 'Get vcpkg'
#        workingDirectory: build
#      - script: |
#          .\bootstrap-vcpkg.bat
#        displayName: Bootstrap vcpkg
#        workingDirectory: build\vcpkg
#      - script: |
#          .\vcpkg.exe install openssl --vcpkg-root ./
#          .\vcpkg.exe list
#        displayName: Install OpenSSL
#        workingDirectory: build\vcpkg
#      - script: |
#          git clone https://github.com/oatpp/oatpp
#          MD oatpp\build
#        displayName: 'Checkout - oatpp'
#        workingDirectory: build
#      - script: |
#          cmake -DOATPP_BUILD_TESTS=OFF ..
#          cmake --build . --target INSTALL
#        displayName: 'Build - oatpp'
#        workingDirectory: build\oatpp\build
#      - script: |
#          set OPENSSL_ROOT_DIR="$BUILD_SOURCESDIRECTORY/build/vcpkg/installed/x86-windows"
#          cmake -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake ..
#          cmake --build .
#        displayName: 'Build Module'
#        workingDirectory: build
#      - script: |
#          module-tests.exe
#        displayName: 'Test'
#        workingDirectory: build\test\Debug\